name = "cfr2-worker"
main = "src/index.js"
compatibility_date = "2025-04-07"

# R2 storage settings
[[r2_buckets]]
binding = "mybinding"
bucket_name = "mybucket"

# Environment variables
[vars]
ALLOWED_ORIGINS = "*"